import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from datetime import datetime
import pytz

# Edmonton timezone
EDMONTON_TZ = pytz.timezone("America/Edmonton")

# Your email (you + team copy)
SELEMANI_EMAIL = "selemaniseif12@yahoo.com"


def build_google_calendar_link(topic, start_dt, end_dt, meeting_link):
    # Google Calendar requires UTC timestamps in YYYYMMDDTHHMMSSZ format
    start_utc = start_dt.astimezone(pytz.utc).strftime("%Y%m%dT%H%M%SZ")
    end_utc = end_dt.astimezone(pytz.utc).strftime("%Y%m%dT%H%M%SZ")

    return (
        "https://calendar.google.com/calendar/render?action=TEMPLATE"
        f"&text={topic}"
        f"&dates={start_utc}/{end_utc}"
        f"&details=Meeting Link: {meeting_link}"
        "&location=Online"
    )


def build_ics_file(topic, start_dt, end_dt, meeting_link):
    ics_content = f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Your Company//Consultation Scheduler//EN
BEGIN:VEVENT
UID:{start_dt.timestamp()}
DTSTAMP:{datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")}
DTSTART:{start_dt.astimezone(pytz.utc).strftime("%Y%m%dT%H%M%SZ")}
DTEND:{end_dt.astimezone(pytz.utc).strftime("%Y%m%dT%H%M%SZ")}
SUMMARY:{topic}
DESCRIPTION:Join the meeting: {meeting_link}
LOCATION:Online
END:VEVENT
END:VCALENDAR
"""
    return ics_content


def send_meeting_email(client_email: str, meeting_link: str, date: str, time: str, topic: str):
    # Convert date + time into datetime objects
    start_dt = EDMONTON_TZ.localize(datetime.strptime(f"{date} {time}", "%Y-%m-%d %H:%M"))
    end_dt = start_dt.replace(minute=start_dt.minute + 30)  # 30‑minute meeting

    # Build Google Calendar link
    google_link = build_google_calendar_link(topic, start_dt, end_dt, meeting_link)

    # Build ICS file
    ics_data = build_ics_file(topic, start_dt, end_dt, meeting_link)

    # HTML email body
    html_body = f"""
    <h2>Your Consultation Meeting is Scheduled</h2>
    <p><strong>Topic:</strong> {topic}</p>
    <p><strong>Date:</strong> {date}</p>
    <p><strong>Time:</strong> {time} (Edmonton Time)</p>
    <p><strong>Meeting Link:</strong> <a href="{meeting_link}">{meeting_link}</a></p>
    <br>
    <p><a href="{google_link}" style="padding:10px 15px;background:#007bff;color:white;text-decoration:none;border-radius:5px;">
        Add to Google Calendar
    </a></p>
    <br>
    <p>This message was automatically generated by your biosensing API system.</p>
    """

    # Build email
    msg = MIMEMultipart()
    msg["Subject"] = f"Consultation Meeting Scheduled — {topic}"
    msg["From"] = "selemaniseif1974@gmail.com"
    msg["To"] = client_email

    # Add HTML body
    msg.attach(MIMEText(html_body, "html"))

    # Attach ICS file
    attachment = MIMEApplication(ics_data, _subtype="ics")
    attachment.add_header("Content-Disposition", "attachment", filename="meeting.ics")
    msg.attach(attachment)

    # Recipients: client + you + team (same as you)
    recipients = [client_email, SELEMANI_EMAIL, SELEMANI_EMAIL]

    # SMTP send
    smtp_server = "smtp.gmail.com"
    smtp_port = 587
    smtp_user = "selemaniseif1974@gmail.com"
    smtp_password = "fgzpiqpsftuzmtdm"

    server = smtplib.SMTP(smtp_server, smtp_port)
    server.starttls()
    server.login(smtp_user, smtp_password)
    server.sendmail(smtp_user, recipients, msg.as_string())
    server.quit()
