from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import smtplib
from email.mime.text import MIMEText

# Database imports
from sqlalchemy.orm import Session
from app.database import SessionLocal
from app.models.consulting_model import ConsultingRequestModel

router = APIRouter(prefix="/consulting", tags=["Consulting"])

# ---------------------------
# Data Model (Pydantic)
# ---------------------------
class ConsultingRequest(BaseModel):
    name: str
    email: str
    organization: str | None = None
    api_key: str | None = None
    project_description: str
    services: list[str]


# ---------------------------
# Save to Database (Minimal)
# ---------------------------
def save_request_to_db(payload: ConsultingRequest):
    db: Session = SessionLocal()
    entry = ConsultingRequestModel(
        name=payload.name,
        email=payload.email,
        organization=payload.organization,
        api_key=payload.api_key,
        project_description=payload.project_description,
        services=",".join(payload.services)
    )
    db.add(entry)
    db.commit()
    db.close()


# ---------------------------
# Email Sender (GMAIL → YAHOO FIX)
# ---------------------------
def send_email_to_selemani(payload: ConsultingRequest):
    subject = "New Consulting Request Submitted"
    body = f"""
A new consulting request has been submitted.

Name: {payload.name}
Email: {payload.email}
Organization: {payload.organization}
API Key: {payload.api_key}
Project Description: {payload.project_description}
Services Requested: {", ".join(payload.services)}

This message was automatically generated by your biosensing API system.
"""

    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = "selemaniseif1974@gmail.com"
    msg["To"] = "selemaniseif12@yahoo.com"   # ⭐ FIX: Gmail → Yahoo

    smtp_server = "smtp.gmail.com"
    smtp_port = 587
    smtp_user = "selemaniseif1974@gmail.com"
    smtp_password = "fgzpiqpsftuzmtdm"   # <-- NO SPACES

    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(smtp_user, smtp_password)
        server.sendmail(
            smtp_user,
            ["selemaniseif12@yahoo.com"],   # ⭐ FIX: Gmail → Yahoo
            msg.as_string()
        )
        server.quit()
    except Exception as e:
        print("Email sending failed:", e)
        raise HTTPException(status_code=500, detail="Failed to send email notification.")


# ---------------------------
# POST ROUTE
# ---------------------------
@router.post("")
def submit_consulting_request(payload: ConsultingRequest):
    print("Received consulting request:", payload.dict())

    # 1. Save to database (never lose client data)
    save_request_to_db(payload)

    # 2. Send email
    send_email_to_selemani(payload)

    return {"message": "Your consulting request was delivered successfully and emailed to Selemani."}
